name: Deploy to AWS ECS

on:
  workflow_dispatch:  # Menjadikan workflow ini hanya berjalan saat ditekan tombol

env:
  AWS_REGION: ap-southeast-1
  ECS_CLUSTER: produksi-stag
  ECS_SERVICE: produksi-web-fe
  TASK_FAMILY: produksi-web
  ECR_REGISTRY: 904233128516.dkr.ecr.ap-southeast-1.amazonaws.com
  ECR_REPOSITORY: produksi/web-fe

jobs:
  deploy:
    name: Deploy to ECS (Manual Trigger)
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Register New Task Definition Revision
      id: register-task
      run: |
        NEW_TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY)
        echo $NEW_TASK_DEF | jq '.taskDefinition.containerDefinitions[0].image="ECR_REGISTRY/'$ECR_REPOSITORY':latest"' > new-task-def.json
        NEW_REVISION=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json | jq -r '.taskDefinition.revision')
        echo "NEW_TASK_REVISION=$NEW_REVISION" >> $GITHUB_ENV
          
    - name: Update ECS Service
      run: |
        aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $TASK_FAMILY:$NEW_TASK_REVISION
